### ISSUE TITLE
v0.0.4 can't assign points in development

### ISSUE THREAD

**Issue by AngelFireDK** [Cities2Modding/FindStuff#4]
After updating to v0.0.4 you can't assign points in development. It takes the points but doesn't unlock it. Works fine in v0.0.3. Tried reverting back to v0.0.3 and then installed v0.04 again same issue.

**Comment by 89pleasure** [comment]
Can't reproduce it with latest version. You're still having this issue?

**Comment by AngelFireDK** [comment]
no works just fine now. So have been fixed. 👍
