### ISSUE TITLE
FindStuff v0.0.5 Mod conflict with Water Features v1.0.0

### ISSUE THREAD

**Issue by BagiIT** [Cities2Modding/FindStuff#5]
I tried to use water features mod to add a lake and the manu doesnt show. I contacted the createor of Water Features mod and he found a conflict with FindStuff mod. 

[Mods_Yenyang_Water_Features.log](https://github.com/Cities2Modding/FindStuff/files/14312331/Mods_Yenyang_Water_Features.log)
[Player.log](https://github.com/Cities2Modding/FindStuff/files/14312332/Player.log)

![image](https://github.com/Cities2Modding/FindStuff/assets/56765679/723ca3a3-0600-4a6f-a3ba-41057f23774b)

**Comment by yenyang** [comment]
https://github.com/Cities2Modding/FindStuff/blob/main/FindStuff/Systems/PickerToolSystem.cs

In PickerToolSystem:

 ```
public override System.Boolean TrySetPrefab( PrefabBase prefab )
{
       return true; // If you set this to False it will fix the problem.
}

**Comment by yenyang** [comment]
Thank you for fixing it. :)
