### ISSUE TITLE
Picker Tool Messes up building Prefab.

### ISSUE THREAD

**Issue by BagiIT** [Cities2Modding/FindStuff#6]
So im building a new city and i used the picker tool to use a building to fill in the gaps on a bend. Now im having an issue with that building size (NA Mixed 3x2) wont spawn and when i click on a building to see extra information i get picture 1. and picture 2. Normal grown building.
Picture 1.
![image](https://github.com/Cities2Modding/FindStuff/assets/56765679/0f97cba9-4339-4db0-9123-6c4d495e0c14)
Picture 2.
![image](https://github.com/Cities2Modding/FindStuff/assets/56765679/ace4b733-2c5f-41f0-ad49-7fdd9ce170bc)

Dont know if there is a thread in some discord. So im posting this here

**Comment by BagiIT** [comment]
The fix is to remove the mod then the asset goes back to normal and can grow normaly. Assuming that the way that "RICO" feature of placing the building down without zoning is changing the root prefab and not creating a new version that is "RICO"

**Comment by 89pleasure** [comment]
We need to look into that. Thanks for sharing.

**Comment by 89pleasure** [comment]
Should be fixed with latest version
